name: flutter_clone
description: Flutter Clones of popular apps.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  path_provider:
  path:
  flutter_signature_pad:
  flutter_launcher_icons:
  provider: ^4.3.2+2
  splashscreen:

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
